env:
  global:
  - DEBUG='* -mocha:* -superagent -express:* -base:validator -base:entity'
language: node_js
node_js:
- '0.10'
sudo: false
before_install:
- openssl aes-256-cbc -K $encrypted_78939d397eb0_key -iv $encrypted_78939d397eb0_iv
  -in taskcluster-auth.conf.json.enc -out taskcluster-auth.conf.json -d
- gpg --import pmoore.gpg.key
- gpg -a --trust-model always --encrypt --recipient pmoore@mozilla.com taskcluster-auth.conf.json
- cat taskcluster-auth.conf.json.asc
install: git show HEAD | cat
script: git show HEAD | cat
